### ISSUE TITLE
Add download button

### ISSUE THREAD

**Issue by PabloCarreira** [mediamonks/richmedia-temple-server#48]
Can we add a dowload button to the list of icons below the banner?
This would be great for clients and will help us maintain latest versions of what they are looking in the preview and what they deliver to media agencies.

The download button will just download the .zip file we could store inside the folder. Or even better if we can gzip online the folder that is already targeting to preview the banner.

**Comment by mientjan** [comment]
great idea. yea lets add it

**Comment by mirkovw** [comment]
Has been added in 9.0.5
