### ISSUE TITLE
Globbing not working atm, maybe due to using spreadsheets?

### ISSUE THREAD

**Issue by mm-paulie** [mediamonks/richmedia-temple-server#61]
When you try to glob to npm run dev only certain units it won't work. See this assembla git repo for testing
https://mediamonks.assembla.com/spaces/tme-bmwmini-atomic-assets-toolkit-1/wiki

**Comment by mirkovw** [comment]
Should be fixed in 9.0.5

**Comment by mm-paulie** [comment]
Globbing doesn't work in build yet only dev atm (same issue)
