### ISSUE TITLE
 richmedia-temple-server 9.0.0 and up is very slow and buggy

### ISSUE THREAD

**Issue by mm-paulie** [mediamonks/richmedia-temple-server#63]
Starting stopping npm run dev, which creates those extra richmediarc files, doesn't always directly delete them. If you have a big project then it all becomes very slow.
Tested with this git repo https://mediamonks.assembla.com/spaces/tme-bmwmini-atomic-assets-toolkit-1/wiki

**Comment by mirkovw** [comment]
Try updating to 9.0.5, lots of bug fixes and performance improvements
